export const INITIAL_TEAM = [
  {
    name: 'Ashish Kumar',
    role: 'Founder & CEO',
    category: 'leadership',
    photo: '/images/founder.png',
    linkedin: 'https://www.linkedin.com/in/ashishkumarji/',
    showSocial: true,
    bio: 'Ashish Kumar is the Founder & CEO of MaaJanki Web Tech, recognized under DPIIT Startup India and Udyam MSME. Guided by a mission to turn web architectures and search marketing into revenue engines for businesses, he oversees agency strategy, engineering standards, and enterprise client partnerships.',
    bio2: 'With deep expertise in Next.js 15 full-stack development, technical SEO, Core Web Vitals optimization, and generative AI search (AEO/GEO), Ashish has spearheaded 250+ website launches and ranking campaigns for businesses across India, the US, the UK, and the Middle East.',
    bio3: 'Under his leadership, MaaJanki Web Tech has evolved from a grassroots web development initiative into an internationally recognized full-service digital transformation agency.',
    coreExpertise: [
      'Enterprise Next.js Architecture',
      'Technical SEO & AEO Strategy',
      'Conversion Rate Optimization (CRO)',
      'Core Web Vitals & PageSpeed',
      'AI Search Engine Optimization',
      'Full-Stack System Engineering',
      'Organic Traffic Scaling',
      'B2B Digital Transformation'
    ],
    tags: ['Vision', 'Leadership', 'Next.js 15', 'Enterprise SEO', 'Full-Stack Architecture', 'Brand Growth'],
    order: 1,
    isActive: true,
  },
  {
    name: 'Co-Founder',
    role: 'Co-Founder',
    category: 'leadership',
    photo: '/images/pages/main-services-pages/our-service-banner-image-Maajanki-Web-Tech.webp',
    linkedin: '',
    showSocial: false,
    bio: 'Co-Founder at MaaJanki Web Tech, playing a key role in shaping the agency\'s vision, culture, and operational excellence.',
    bio2: '',
    bio3: '',
    coreExpertise: [],
    tags: ['Co-Founder', 'Leadership'],
    order: 2,
    isActive: false,
  },
  {
    name: 'Rahul Verma',
    role: 'Lead Full-Stack Engineer',
    category: 'squad',
    photo: '/images/pages/main-services-pages/Home-page-image-Maajanki.webp',
    linkedin: '',
    showSocial: false,
    bio: 'Rahul leads web engineering at MaaJanki Web Tech, specializing in Next.js App Router architectures, Node.js REST & GraphQL APIs, database indexing, and performance optimization.',
    bio2: 'He ensures all web applications maintain sub-second load times, 99.9% uptime, responsive fluid aesthetics, and strict Core Web Vitals compliance (LCP < 2.5s).',
    bio3: 'Rahul works closely with design and backend teams to implement modern, secure, and scalable web solutions that deliver seamless digital experiences.',
    coreExpertise: [
      'Next.js 15 & React Server Components',
      'Node.js REST & GraphQL APIs',
      'MongoDB & Database Indexing',
      'TypeScript & State Management',
      'API Security & Authentication',
      'Responsive Mobile-First UI',
      'TailwindCSS & Modern CSS',
      'Cloud Deployment & Docker CI/CD'
    ],
    tags: ['React', 'Next.js', 'Node.js', 'MongoDB', 'PostgreSQL', 'TailwindCSS', 'API Security'],
    order: 2,
    isActive: true,
  },
  {
    name: 'Priya Singh',
    role: 'Senior SEO Strategist',
    category: 'squad',
    photo: '/images/pages/main-services-pages/seo-banner-image-Maajanki.webp',
    linkedin: '',
    showSocial: false,
    bio: 'Priya is an analytical search strategist with 4+ years of expertise in semantic keyword clustering, technical site audits, backlink syndication, and programmatic local SEO.',
    bio2: 'She works hands-on with client sites to build authoritative schema graphs, enhance Google Search Console metrics, and rank commercial high-intent keywords to the top 3 spots.',
    bio3: 'She stays ahead of Google algorithm updates and emerging AI discovery engines to keep client rankings stable, resilient, and growing.',
    coreExpertise: [
      'Semantic Keyword Clustering',
      'Technical SEO Crawl Audits',
      'Schema.org Structured Data',
      'High-Authority Link Building',
      'Google Search Console Optimization',
      'Programmatic Local SEO',
      'Competitor Gap Analysis',
      'AEO/GEO & Perplexity AI Search'
    ],
    tags: ['Technical SEO', 'Keyword Research', 'Schema Markup', 'Backlinks', 'AEO/GEO', 'Google Analytics'],
    order: 3,
    isActive: true,
  },
  {
    name: 'Neha Sharma',
    role: 'Lead UI/UX & Brand Designer',
    category: 'squad',
    photo: '/images/pages/main-services-pages/ui-ux-design-banner-image-Maajanki-Web-Tech.webp',
    linkedin: '',
    showSocial: false,
    bio: 'Neha crafts user-centered visual systems, brand design systems, and wireframes that transform visitors into paying customers. Her designs balance aesthetic beauty with conversion rate optimization.',
    bio2: 'From Figma interactive prototypes and responsive typography scales to brand logo identities and micro-animations, she gives every client project an unforgettable premium look.',
    bio3: 'She focuses on creating cohesive brand experiences across web, mobile, and social touchpoints that drive high engagement and brand affinity.',
    coreExpertise: [
      'Figma Design Systems & Tokens',
      'User Journey & Wireframing',
      'Conversion-Focused Landing Pages',
      'Micro-Interactions & Motion UX',
      'Brand Visual Identity & Guidelines',
      'Typography & Color Theory',
      'Mobile App UI Design',
      'Interactive Prototype Testing'
    ],
    tags: ['UI/UX Design', 'Figma', 'Visual Identity', 'Typography', 'Wireframing', 'Design Systems'],
    order: 4,
    isActive: true,
  },
  {
    name: 'Amit Patel',
    role: 'Performance Marketing Specialist',
    category: 'squad',
    photo: '/images/pages/main-services-pages/performance-marketing-banner-image-MaaJanki-Web-Tech.webp',
    linkedin: '',
    showSocial: false,
    bio: 'Amit manages paid acquisition funnels across Meta Ads, Google Ads, and LinkedIn Campaign Manager, having managed over ₹50L+ in ad budgets with consistently high ROAS.',
    bio2: 'He blends data analytics, creative A/B copy testing, and audience retargeting to lower cost-per-lead (CPL) and build scalable conversion engines.',
    bio3: 'His analytical mindset and data-backed testing methodology ensure marketing budgets generate positive, measurable returns on ad spend.',
    coreExpertise: [
      'Meta Ads & Advantage+ Funnels',
      'Google Search & Performance Max',
      'High-ROAS Audience Retargeting',
      'Ad Creative & Copy A/B Testing',
      'Conversion Tracking & GA4 Setup',
      'Lead Generation & CPL Reduction',
      'LinkedIn B2B Advertising',
      'Budget Scaling & ROI Optimization'
    ],
    tags: ['Google Ads', 'Meta Ads', 'PPC Management', 'Conversion Tracking', 'Funnel Optimization', 'ROI Scaling'],
    order: 5,
    isActive: true,
  },
  {
    name: 'Rohan Gupta',
    role: 'Social Media & Motion Creative',
    category: 'squad',
    photo: '/images/pages/main-services-pages/smo-banner-image-MaaJanki.webp',
    linkedin: '',
    showSocial: false,
    bio: 'Rohan specializes in brand storytelling, Reels/Shorts production, motion typography, and social media community growth across Instagram, LinkedIn, and YouTube.',
    bio2: 'He combines trending creative hooks with strategic brand positioning to create viral, engaging content that elevates brand visibility and brand affinity.',
    bio3: 'Rohan experiments with modern video editing software and AI visual tools to craft motion assets that capture viewer attention within seconds.',
    coreExpertise: [
      'Reels & YouTube Shorts Production',
      'Motion Graphic Design & VFX',
      'Viral Social Hook Strategy',
      'Brand Storytelling & Scriptwriting',
      'Instagram Community Building',
      'Video Editing & Color Grading',
      'Social Media Calendar Management',
      'Engagement Analytics & Trends'
    ],
    tags: ['Social Media Strategy', 'Motion Design', 'Video Editing', 'Reels Production', 'Brand Storytelling'],
    order: 6,
    isActive: true,
  },
  {
    name: 'Ananya Roy',
    role: 'Content Strategist & Copywriter',
    category: 'squad',
    photo: '/images/pages/main-services-pages/content-writing-banner-maajanki-web-tech.webp',
    linkedin: '',
    showSocial: false,
    bio: 'Ananya produces high-converting landing page copy, technical SEO blog articles, email outreach sequences, and brand pitch decks tailored to audience intent.',
    bio2: 'Her content combines engaging storytelling with rigorous keyword research to capture AI search citations and drive organic search engine traffic.',
    bio3: 'She ensures brand messaging speaks directly to client pain points while maintaining clarity, grammatical polish, and search ranking signals.',
    coreExpertise: [
      'High-Converting Sales Landing Pages',
      'In-Depth Technical SEO Blog Guides',
      'Email Marketing & Drip Sequences',
      'Brand Voice & Positioning Guidelines',
      'AI-Optimized Search Articles',
      'Pitch Decks & Whitepapers',
      'Content Audits & Gap Analysis',
      'Meta Descriptions & Snippet Optimization'
    ],
    tags: ['Copywriting', 'SEO Content', 'Email Sequences', 'Brand Messaging', 'Technical Writing'],
    order: 7,
    isActive: true,
  }
];
